config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'shops#index'

  get '/allorders', to: 'orders#index', format: false
  resources :shops do
    resources :carts, only: [:index, :show, :new, :create, :destroy] do
      resources :orders do
        resources :past_orders, only: [:index, :new, :create, :destroy]
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_one :order
  belongs_to :shop

  after_create :create_order

  private

  def create_order
    Order.create(cart: self)
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :shops
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :cart
  has_one :past_order

  after_create :new_past_order

  def compute_order
    @shop = Shop.where(shop_id: @shop_id)
    @cart = Cart.where(cart_id: @cart_id)
    @order = Order.where(cart_id: @cart_id).first
    @code_order = @order.cart.shop.code
  end

  private

  def new_past_order
    PastOrder.new(order: self)
  end

end

app/models/past_order.rb
class PastOrder < ApplicationRecord
  belongs_to :order

end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :category
  has_many :carts
  has_many :orders, through: :carts

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :carts
  has_many :orders, through: :carts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def index
    @user = User.find(current_user.id)
    @shops = Shop.all
    @carts = Cart.all
    #@shop = Shop.find(params[:shop_id])
  end

  def new
    @shop = Shop.find(params[:shop_id])
    @user = User.find(current_user.id)
    @cart = Cart.new
  end

  def create
    @shop = Shop.find(params[:shop_id])
    @cart = Cart.new
    @cart.shop = @shop
    @cart.user = current_user
    @cart.save

    if @cart.save
      @order = @cart.order
      redirect_to edit_shop_cart_order_path(@shop, @cart, @order)
    else
      render :new
    end
  end

  def show
    @cart = Cart.find(params[:id])
  end

  def destroy
    @cart = Cart.find(params[:id])
    @order = Order.find(params[:id])
    @shop = Shop.find(params[:id])
    @cart.destroy

    redirect_to root_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def new
    @shop = Shop.find(params[:shop_id])
    @cart = Cart.find(params[:cart_id])
    @user = User.find(current_user.id)
    @order = Order.new
  end

  def create
    @shop = Shop.find(params[:shop_id])
    @cart = Cart.find(params[:cart_id])
    @user = User.find(current_user.id)
    @order = Order.new
    @order.cart = @cart
    @order.code_validated == false
    @order.save


    if @cart.save
      redirect_to edit_shop_cart_order_path(@shop, @cart)
    else
      render :new
    end
  end

  def edit
    @shop = Shop.find(params[:shop_id])
    @cart = Cart.find(params[:cart_id])
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    @order.date_order = DateTime.now
    @order.code_validated_time = DateTime.now

    if @order.update(order_params)
      redirect_to allorders_path
    else
      render :edit
    end
  end

  def show
    @order = Order.find(params[:id])
  end

  def index #allorders button in navbar
    @orders = Order.all
  end

  def destroy
    @order = Order.find(params[:id])
    @cart = Cart.find(params[:cart_id])
    @user = User.find(current_user.id)

    @order.destroy

    redirect_to allorders_path
  end

  private

  def order_params
    params.require(:order).permit(:code_validated)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/past_orders_controller.rb
class PastOrdersController < ApplicationController
  def new
    @order = Order.find(params[:order_id])
    @past_order = PastOrder.new
  end

  def create
    @order = Order.find(params[:order_id])
    @past_order = PastOrder.new
    @past_order.order = @order
    @past_order.save

    if @past_order.save
      redirect_to shop_cart_order_past_order_path(@shop, @cart, @order)
    else
      render :new
    end
  end

  def destroy
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new
    super
    puts "hi there============>>>>>>>>" 
  end

  def create
    song = Song.new(name: "kaushik",play: 1)
    song.save
    puts "hi there============>>>>>>>>"
    # add custom create logic here
  end
  def update
    super
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  #before_action :set_shop, only: [:show, :edit, :update, :destroy]

  def index
    @shops = Shop.all
  end

  def show
    @shop = Shop.find(params[:id])
  end

  def new
    @shop = Shop.new(shop_params)
    @shop.save
  end

  def create
    @category = Category.find(params[:category_id])
    @shop = Shop.new(shop_params)
    @shop.category = @category
    params[:shop]
  end

  def edit
    @shop = Shop.find(params[:id])
  end

  def update
    @shop = Shop.find(params[:id])
    @shop.update(shop_params)
    @shop.save
  end

  def destroy
    @shop = Shop.find(params[:id])
    @shop.destroy
  end

  private

  def shop_params
    params.require(:shop).permit(:name, :location, :code, :description, :price, :ex_price, :nb_box)
  end

  # def set_shop
  # @shop = Shop.find(params[:id])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carts/create.html.erb
<h1>Carts#create</h1>
<p>Find me in app/views/carts/create.html.erb</p>

app/views/carts/destroy.html.erb
<h1>Carts#destroy</h1>
<p>Find me in app/views/carts/destroy.html.erb</p>

app/views/carts/index.html.erb
<div class=container>
  <div class="row">
      <div class="col-sm-12">

      <% @carts.reverse.each do |cart| %>
        <%= link_to shop_carts_path(@carts) do %>
          <div class="myorder-cart", style="padding: 10px 0 0 20px;">
            <div class=cart-info>
              <p style="font-size: 14px; color:black; font-weight: 500;"><%= cart.shop.name%></p>
            </div>
            <div class=cart-info style="color: #625F5F;">
              <p><%= cart.created_at%></p>
              <p style="font-weight: 300; font-size:13px;"><%= cart.shop.price%> SGD</p>

                <%= link_to root_path, class: "btn btn-action", :method => :delete do %> X
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>

    </div>
  </div>
</div>

app/views/carts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">

        <div class="cart-container">
            <div class="big-shop-card-header">
                <div class="shop-card-logo-avatar" id="cart-avatar">
                </div>
                <div class="cart-shop-title">
                  <h4><%= @shop.name%></h4>
                </div>
            </div>

            <div class="big-shop-card" id="big-shop-cart">
            </div>

            <div class="order-title">
              <h3 style="margin-top:10px;">ORDER</h3>
            </div>

            <div class="cart-info-container">
              <div class="cart-info">
                <p id=titles-info>Pick-up time</p>
                <p>Today 7:30pm - 8:30pm</p>
              </div>
              <div class="cart-info">
                <p id=titles-info>Availabilities</p>
                <%= @shop.nb_box %></div>
              <div class="cart-info">
                <p id=titles-info>Directions</p>
                <%=  @shop.location%></div>
                <div class="cart-info">
                  <p> To save your deal, pre-order it by clicking on "Save order" and go to <%= @shop.name %> at the specified time.</p>
                </div>
            </div>

            <div class="cart-total">
            </div>

            <div class="col-sm-12">
                  <%= simple_form_for [@shop, @cart] do |f|%>
                    <%= f.submit "SAVE ORDER", class:"btn btn-action btn-duck-blue btn-medium border-rad",style:"margin-top:20%;", id:"btn-save-order" %>
                  <% end %>
            </div>

    </div>
  </div>
</div>

app/views/carts/show.html.erb
<p>cart#show</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' if user_signed_in?%>
    <%= render 'shared/bottomnavbar' if user_signed_in?%>

    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <!-- <p class="notice"><%= notice %></p> -->
    <!-- <p class="alert"><%= alert %></p> -->
  </body>
</html>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/destroy.html.erb
<h1>Orders#destroy</h1>
<p>Find me in app/views/orders/destroy.html.erb</p>

app/views/orders/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">

        <div class="cart-container">
            <div class="big-shop-card-header">
                <div class="shop-card-logo-avatar" id="cart-avatar">
                </div>
                <div class="cart-shop-title">
                  <h4><%= @order.cart.shop.name%></h4>
                </div>
            </div>

            <div class="big-shop-card" id="big-shop-cart">
            </div>

            <div class="order-title">
              <h3 style="margin-top: 10px;"> ORDER PICKING-UP</h3>
            </div>

            <div class="cart-info-container" style="margin-top: 10px; margin-bottom: 0px;">
              <div class="cart-info" style="height: 20px;">
                <p>Pick-up time</p>
                <p>Today : 7.30Pm - 8.30pm</p>
              </div>
              <div class="cart-info">
                <p>Directions</p>
                <%= @order.cart.shop.location%></div>
              <div class="cart-info" id="total-order">
                <p></p><p>Total</p>
                <p style="margin-right: 50px;"><%= @order.cart.shop.price%> SGD</p>
              </div>
              <p style="font-size: 14px; margin-left: 10px;margin-bottom: 0px;">I confirm I let the food merchant validate my order at the <%= @order.cart.shop.name%>'s cachier and I have been given the order.</p>
            </div>


            <div class="col-sm-12">
                  <%= simple_form_for([@shop, @cart, @order]) do |f|%>
                    <%= f.input :code_validated, as: :boolean, checked_value: true, unchecked_value: false, style:"margin-bottom: 0px;"%>
                    <%= f.submit "CONFIRM", class:"btn btn-action btn-duck-blue btn-medium border-rad"%>
                  <% end %>

            </div>
<p style="height:40px"></p>
    </div>
  </div>
</div>

app/views/orders/index.html.erb
<div class=container>
  <div class="row">
      <div class="col-sm-12">

      <% @orders.reverse.each do |order| %>
        <%= link_to edit_shop_cart_order_path(order.cart.shop.id, order.cart.id, order) do %>
          <div class="myorder-cart", style="padding: 10px 0 0 20px;">
            <div class=cart-info>
              <p style="font-size: 14px; color:black; font-weight: 500;"><%= order.cart.shop.name%></p>
               <p style="font-size: 14px; color:black; font-weight: 500;"><%= order.code_validated%></p>
            </div>
            <div class=cart-info style="color: #625F5F;">
              <p><%= order.created_at%></p>
              <p style="font-weight: 300; font-size:13px;"><%= order.cart.shop.price%> SGD</p>

            </div>
          </div>
        <% end %>
      <% end %>

    </div>
  </div>
</div>

app/views/orders/new.html.erb
<h1>Orders#new</h1>
<p>Find me in app/views/orders/new.html.erb</p>

app/views/orders/show.html.erb
order#show

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/past_orders/create.html.erb
<h1>PastOrders#create</h1>
<p>Find me in app/views/past_orders/create.html.erb</p>

app/views/past_orders/index.html.erb
<h1>PastOrders#index</h1>
<p>Find me in app/views/past_orders/index.html.erb</p>

app/views/past_orders/new.html.erb
<h1>PastOrders#new</h1>
<p>Find me in app/views/past_orders/new.html.erb</p>

app/views/shared/_bottomnavbar.html.erb
<div class="navbar-bottom navbar-fixed-bottom">
  <!-- Search bar -->

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-top-right">
    <div class="bottom-navbar">
        <%= link_to shops_path do %>
          <i class="fa fa-cookie-bite"></i> <%= t(".food", default: "Find food") %>
        <% end %>
         <%= link_to "#" do %>
         <i class="fa fa-map-marked"></i>  <%= t(".map", default: "Map") %>
         <% end %>
        <%= link_to allorders_path do %>
          <i class="fa fa-shopping-cart"></i>  <%= t(".orders", default: "My orders") %>
        <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <div class="alert-message-holder">
    	<%= notice %>
    </div>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <div class="alert-message-holder">
    	<%= alert %>
    </div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-top">
  <!-- Search bar -->
  <form id="search-shop" class="form-inline ">
    <input type="text" class="form-control navbar-search-bar" placeholder="Search shops">
  </form>

  <!-- Dropdown list appearing on mobile only -->
<div class="navbar-top-item hidden-md hidden-lg">
  <div class="dropdown">
    <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
    <ul class="dropdown-menu dropdown-menu-right navbar-top-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out-alt"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
</div>


  <!-- Right Navigation on desktop -->
  <div class="navbar-top-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-top-item">
        <div class="dropdown">
          <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
          <ul class="dropdown-menu dropdown-menu-right navbar-top-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-top-item navbar-top-link" %>
    <% end %>
  </div>

app/views/shops/create.html.erb
<h1>Shops#create</h1>
<p>Find me in app/views/shops/create.html.erb</p>

app/views/shops/destroy.html.erb
<h1>Shops#destroy</h1>
<p>Find me in app/views/shops/destroy.html.erb</p>

app/views/shops/edit.html.erb
<h1>Shops#edit</h1>
<p>Find me in app/views/shops/edit.html.erb</p>

app/views/shops/index.html.erb
<div class=container>
  <div class="row">
    <div class="col-sm-12" id=margin-bottom-row-class>

      <%@shops.each do |shop| %>
        <%= link_to shop_path(shop) do %>
          <div class="shop-card">
            <div class="shop-card-header">
              <div class="shop-card-logo-avatar">
              </div>
              <div class="shop-card-price">
                <p>$<%= shop.price%></p>
              </div>
              <div class="shop-card-title">
                <h4><%= shop.name%></h4>
              </div>
            </div>
            <div class="shop-card-footer">
              <div>
                <p id="nb-left"><%=shop.nb_box%> left</p>
                <p id="shop-addresss"><%= shop.location %></p>
              </div>
              <div>
                <p id="collection-time">7.30pm - 8.30pm</p>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>

    </div>
  </div>
</div>

app/views/shops/new.html.erb
<h1>Shops#new</h1>
<p>Find me in app/views/shops/new.html.erb</p>

app/views/shops/show.html.erb
<div class="shop-title">
  <h4><%=@shop.name%></h4>
</div>

<div class=container>
  <div class="row">
    <div class="col-sm-12">

        <div class="big-shop-card pos-rel">

          <div class="big-shop-card-header">
            <p><%=@shop.nb_box%> left</p>
            <p>7.30pm - 8.30pm</p>
            <div class="shop-card-logo-avatar">
            </div>
            <div class="shop-card-title">
            </div>
          </div>

          <div class="big-shop-card-footer navbar-fixed-bottom">
            <div class="big-shop-card-price">
              <div class="ex-price-card">
                <p>$<%= @shop.ex_price%></p>
              </div>
              <p>$<%= @shop.price%></p>
            </div>
          </div>
        <div>
          <%= link_to new_shop_cart_path(@shop.id) do %>
            <div class="btn btn-action btn-add-cart" style="margin-top:60%; margin-right:0px; margin-left:40%;">
                 +
            </div>
          <% end %>
        </div>
        </div>
    </div>

    <div class="description-container">
      <p>Come and get your deal among a selection from this <%= @shop.description %>: pastries, smoothies, sandwiches... depending on what was left at the end of the day.</p>
      <p>Don't forget to bring your bag to reduce the use of disposable plastics.</p>
      <p>Thank you for your contribution to the fight against food waste !</p>
      <p style="height: 30px"></p>
    </div>

    <div class="direction-container">
      <p><%= @shop.location %></p>
    </div>

  </div>
</div>

app/views/shops/update.html.erb
<h1>Shops#update</h1>
<p>Find me in app/views/shops/update.html.erb</p>